### ISSUE TITLE
[Aroma 1997's Dimensional World] Crash

### ISSUE THREAD

**Issue by VallenFrostweaver** [AllTheMods/ATC#14]
Crashed out when mining (stone) blocks touching the portal from the mining dimension. Crash report here:
https://pastebin.com/T1FbT1Rz

EDIT: Kashcah had mined out the blocks while I (in the overworld) was taking an osmium sharpening kit (Tinkers' Construct/Mekanism) from a smeltery mold in a table. Now when I log in I crash her and I off the server though she can log into the server.

EDIT#2: Removing the portal and replacing it allowed me to log on with no side effects.

**Comment by OrdinatorStouff** [comment]
I was able to reproduce this by throwing a piece of cobblestone on/in the portal. According to Aroma this should already be fixed so a mod update should be all that's needed
https://pastebin.com/SeNXgdar

**Comment by OrdinatorStouff** [comment]
closed in pack version 2.0.3 (tested and no longer crashing)
