### ISSUE TITLE
Custom Recipes Wood Essence -- Modded Logs

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATC#4]
It would be trivial to add a loop function in crafttweaker to allow wood essence to "dupe" any log type. 

For example, 4 wood essence around a forestry log would yield 16 of that same log.

Also consider nerfing wood essence crafting quantity. I know it's just wood but still, 3 essence -> 16 logs is a lot.

**Comment by BloodWorkXGaming** [comment]
You might be even able to add this as a recipe function, to make input =
output.
Might be not work for jei correctly tho

OrdinatorStouff <notifications@github.com> schrieb am So., 23. Juli 2017,
00:36:

**Comment by OrdinatorStouff** [comment]
Personal note: For update, review options provided by attained drops / resourceful crops for this instead of mystical ag

**Comment by OrdinatorStouff** [comment]
MA removed -- resourcefulcrops will have custom seeds hand-made
